### ISSUE TITLE
Linter runs on files it should likely not run on by default

### ISSUE THREAD

**Issue by johnbrett** [standard/vscode-standard#22] opened 2017-04-19 08:52 UTC
- [1.1.0] StandardJS version? (I presume this means the plugin version?)
- [1.11.1] VSCode version?

Hey great job on this plugin first of all 👍 

I noticed the plugin tries to lint files in a `node_modules` directory if I view them. This should be disabled by default I believe.

I noticed it also tries to debug scripts like `vm.js` (`debug:<node_internals>/vm.js`) that would likely be exposed when debugging, which I don't have control over.

**Comment by doughsay** [comment] 2017-05-28 01:16
Please see here the description of how StandardJS ignoring works: https://standardjs.com/#how-do-i-ignore-files

Note that it says certain files/folder are ALWAYS ignored (node_modules/, coverage/, vendor/, *.min.js, bundle.js, and files/folders that begin with . like .git/), and you can add custom ignore rules to package.json.

This plugin should preferably honor these settings. Other than that, great extension, thanks!

**Comment by chenxsan** [comment] 2017-05-28 02:33
@doughsay The extension make use of [`lintText`](https://github.com/chenxsan/vscode-standardjs/blob/master/eslint-server/src/server.ts#L660) API instead of `lintFiles`, that's why the [ignore function fails](https://github.com/Flet/standard-engine#full-set-of-opts), will fix it when i have time :)

**Comment by chenxsan** [comment] 2017-06-21 05:14
@johnbrett @doughsay Just published 1.1.5 to fix it, please upgrade it.

**Comment by chenxsan** [comment] 2017-06-22 01:19
@johnbrett @doughsay I'm going to close it, if you still have any problem, I'll reopen it.

**Closed as completed by chenxsan** 2017-06-22 01:19 UTC
Labels: bug

**Comment by doughsay** [comment] 2017-06-22 02:50
Thanks!  It's working as intended now.
